# Custom Language File for Launcher Customizer

[ejs.app]
title = "쩡코몬 Launcher"

[ejs.landing]
mediaLinkURL = "https://www.youtube.com/@Co.%EA%B3%A8%EC%83%81"
mediaGitHubURL = ""
mediaXURL = "#"
mediaInstagramURL = "https://discord.gg/N7QuDe6dUn"
mediaYouTubeURL = "https://www.youtube.com/@%EC%A9%A1%EA%B0%80/videos"
mediaDiscordURL = "https://discord.gg/7uCGKmk9"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "쩡코몬 서버에 오신걸 환영합니다"
welcomeDescription = "쩡코몬서버"
welcomeDescCTA = "규칙을 준수해 주시면 감사하겠습니다!"
